### ISSUE TITLE
sous chef must have a slug

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#106]
00:42:37 | newslynx.tasks.default-100 | Updating sous chef: "internal-refresh-content-comparisons"
00:42:37 | newslynx.cli.init-111 | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newslynx/cli/init.py", line 106, in run
    default.org()
  File "/usr/local/lib/python2.7/dist-packages/newslynx/tasks/default.py", line 59, in org
    sous_chefs(org)
  File "/usr/local/lib/python2.7/dist-packages/newslynx/tasks/default.py", line 91, in sous_chefs
    for sc, fp in init.load_sous_chefs():
  File "/usr/local/lib/python2.7/dist-packages/newslynx/init.py", line 93, in load_sous_chefs
    for sc, fp in findsc(sous_chef_dir):
  File "/usr/local/lib/python2.7/dist-packages/newslynx/init.py", line 89, in findsc
    sc = sous_chef_schema.load(fp)
  File "/usr/local/lib/python2.7/dist-packages/newslynx/models/sous_chef_schema.py", line 50, in load
    raise SousChefSchemaError(msg)
SousChefSchemaError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newslynx/models/sous_chef_schema.py", line 47, in load
    return validate(sc, fp)
  File "/usr/local/lib/python2.7/dist-packages/newslynx/models/sous_chef_schema.py", line 99, in validate
    raise SousChefSchemaError(msg)
SousChefSchemaError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newslynx/models/sous_chef_schema.py", line 65, in validate
    _validate_sous_chef_json_schema(sc)
  File "/usr/local/lib/python2.7/dist-packages/newslynx/models/sous_chef_schema.py", line 218, in _validate_sous_chef_json_schema
    raise SousChefSchemaError('A SousChef must have a slug!')
SousChefSchemaError: A SousChef must have a slug!

failed on file /root/.newslynx/sous-chefs/newslynx-sc-rss/newslynx_sc_rss.egg-info/pbr.json

failed on file /root/.newslynx/sous-chefs/newslynx-sc-rss/newslynx_sc_rss.egg-info/pbr.json

**Comment by mhkeller** [comment]
this occurs on `newslynx init`

**Comment by mhkeller** [comment]
Note, i got to this error after doing `pip install .` to avoid  this issue https://github.com/newslynx/opportunities/issues/107

**Comment by mhkeller** [comment]
This issue also seems to have resolved itself
