### ISSUE TITLE
CoreQuery is not callable

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#114]
For: 
google-analytics-to-content-device-summaries
google-analytics-to-content-domain-summaries
google-analytics-to-content-timeseries
google-analytics-to-content-domain-facets

```
Traceback (most recent call last):
  File \"/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py\", line 122, in run
    data = sous_chef.cook()
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 126, in cook
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 122, in cook
    data = self.load(data)  # load the data.
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 489, in load
    d = list(data)
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 80, in serialize
    for item in data:
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 157, in run
    for row in self.format(data, prof):
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 471, in format
    for row in self.pre_format(data, prof):
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 461, in pre_format
    for row in data:
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 430, in fetch
    q = prof.core.query(self.METRICS.keys(), self.DIMENSIONS.keys())\\
    TypeError: 'CoreQuery' object is not callable


```

**Comment by abelsonlive** [comment]
looks like stijn changed the API again:

https://github.com/debrouwere/google-analytics/issues/19

**Comment by mhkeller** [comment]
should we dial back to an older version or does that bring up the pyasn error?

**Comment by mhkeller** [comment]
@abelsonlive How onerous is implementation of the new usage?

**Comment by mhkeller** [comment]
It seems it's passing a list of metrics to `core.query`.

I changed to the following via https://github.com/newslynx/newslynx-sc-google-analytics/commit/0e3131e3c6347fd6c0d0dd31647e14a100fb0461

``` py
prof.core.query.metrics(self.METRICS.keys(), self.DIMENSIONS.keys())
```

but now getting this which would make sense if it expects a string and is getting a list.

```
raceback (most recent call last):
  File \"/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py\", line 122, in run
    data = sous_chef.cook()
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 126, in cook
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 122, in cook
    data = self.load(data)  # load the data.
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 275, in load
    d = list(data)
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 80, in serialize
    for item in data:
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 157, in run
    for row in self.format(data, prof):
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 263, in format
    for r in self.pre_format(data, prof):
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 241, in pre_format
    for row in data:
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 186, in fetch
    q = prof.core.query.metrics(self.METRICS.keys(), self.DIMENSIONS.keys())\\
  File \"/usr/local/lib/python2.7/dist-packages/googleanalytics/query.py\", line 389, in metrics
    return self.columns('metric', *metrics)
  File \"/usr/local/lib/python2.7/dist-packages/googleanalytics/utils/functional.py\", line 52, in wrapped_method
    method(obj, *vargs, **kwargs)
  File \"/usr/local/lib/python2.7/dist-packages/googleanalytics/query.py\", line 342, in columns
    for column in self.api.columns.normalize(values, wrap=True):
  File \"/usr/local/lib/python2.7/dist-packages/googleanalytics/utils/functional.py\", line 38, in vectorized_method
    results = [fn(self, value, *vargs, **kwargs) for value in values]
  File \"/usr/local/lib/python2.7/dist-packages/googleanalytics/columns.py\", line 234, in normalize
    return self[value]
  File \"/usr/local/lib/python2.7/dist-packages/addressable/__init__.py\", line 116, in __getitem__
    value = self.get(key)
  File \"/usr/local/lib/python2.7/dist-packages/addressable/__init__.py\", line 132, in get
    if self.cmp(key, candidate):
  File \"/usr/local/lib/python2.7/dist-packages/addressable/__init__.py\", line 41, in iequals
    return equals(a.lower(), b.lower())
    AttributeError: 'list' object has no attribute 'lower'
```

**Comment by mhkeller** [comment]
After [changing to raw query](https://github.com/newslynx/newslynx-sc-google-analytics/commit/81b8d81a010387eec9e31e64eb1e39f62bce4a68), the keynames now must be exact GA names

```
Traceback (most recent call last):\
  File \"/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py\", line 122, in run\
    data = sous_chef.cook()\
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 126, in cook\
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):\
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 122, in cook\
    data = self.load(data)  # load the data.\
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 277, in load\
    d = list(data)\
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 80, in serialize\
    for item in data:\
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 157, in run\
    for row in self.format(data, prof):\
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 265, in format\
    for r in self.pre_format(data, prof):\
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 243, in pre_format\
    for row in data:\
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 194, in fetch\
    r = q.execute()\
  File \"/usr/local/lib/python2.7/dist-packages/googleanalytics/query.py\", line 512, in execute\
    raise errors.InvalidRequestError(diagnostics)
    InvalidRequestError: Parameter \"metrics\" value \"entrances,pageviews,exits,timeOnPage\" does not match the pattern \"ga:.+\"\

    The query you submitted was:\

    sort       \t-ga:dateHour,-ga:pagePath
dimensions \t['hostname', 'pagePath', 'dateHour']
end_date   \t2015-09-10
ids        \tga:35543181
metrics    \t['entrances', 'pageviews', 'exits', 'timeOnPage']
max_results\t1001
start_date \t2015-07-13
start_index\t1\
\

```

**Comment by mhkeller** [comment]
they should be prefixed with `ga:`

**Comment by mhkeller** [comment]
Added the `ga:` prefix and got a few different errors

on `google-analytics-to-content-device-summaries` and `google-analytics-to-content-domain-facets` I get this

```
Traceback (most recent call last):
  File \"/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py\", line 122, in run
    data = sous_chef.cook()
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 126, in cook
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 122, in cook
    data = self.load(data)  # load the data.
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 505, in load
    status_resp = self.api.content.bulk_create_summary(data=d)
  File \"/opt/newslynx/newslynx-core/newslynx/client.py\", line 737, in bulk_create_summary
    return self._request('POST', url, params=params, data=data)
  File \"/opt/newslynx/newslynx-core/newslynx/client.py\", line 93, in _request
    return self._format_response(resp, err)
  File \"/opt/newslynx/newslynx-core/newslynx/client.py\", line 162, in _format_response
    raise err(d['message'])
    RequestError: Bulk endpoints require a list of json objects.
```

on `google-analytics-to-content-timeseries` I get

```
Traceback (most recent call last):
  File \"/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py\", line 122, in run
    data = sous_chef.cook()
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 126, in cook
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 122, in cook
    data = self.load(data)  # load the data.
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 280, in load
    d = list(data)
  File \"/opt/newslynx/newslynx-core/newslynx/sc/__init__.py\", line 80, in serialize
    for item in data:
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 157, in run
    for row in self.format(data, prof):
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 268, in format
    for r in self.pre_format(data, prof):
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 250, in pre_format
    row['datetime'] = self.format_date(row['datetime'], tz=tz)
  File \"/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py\", line 222, in format_date
    dt = datetime.strptime(ds, '%Y%m%d%H')
    TypeError: must be string, not datetime.datetime
```

**Comment by mhkeller** [comment]
full recipe logs

```
11:47:13 *** Listening on recipe...
11:47:37 recipe: newslynx.merlynne.run(u'newslynx_sc_google_analytics.ContentTimeseries', 22, 'newslynx-merlynne-kwargs:e91b06987f75d16c77667e6f2cf6f5e3') (e91b06987f75d16c77667e6f2cf6f5e3)
11:47:43 recipe: newslynx.merlynne.run(u'newslynx_sc_google_analytics.ContentDeviceSummaries', 23, 'newslynx-merlynne-kwargs:85d3e5c4e81a731ada5a450f44147b8d') (85d3e5c4e81a731ada5a450f44147b8d)
11:47:44 Job OK, result = u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py", line 122, in run\n    data = sous_chef.cook()\n  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 126, in cook\n    raise SousChefExecError(format_exc())\nSousChefExecError: Traceback (most recent call last):\n  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 122, in cook\n    data = self.load(data)  # load the data.\n  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 281, in load\n    d = list(data)\n  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 80, in serialize\n    for item in data:\n  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 158, in run\n    for row in self.format(data, prof):\n  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 269, in format\n    for r in self.pre_format(data, prof):\n  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 251, in pre_format\n    row[\'datetime\'] = self.format_date(row[\'datetime\'], tz=tz)\n  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 223, in format_date\n    dt = datetime.strptime(ds, \'%Y%m%d%H\')\nTypeError: must be string, not datetime.datetime\n\n'
11:47:44 Result is kept for 60 seconds
11:47:44
11:47:44 *** Listening on recipe...
11:47:48 recipe: newslynx.merlynne.run(u'newslynx_sc_google_analytics.ContentDomainFacets', 24, 'newslynx-merlynne-kwargs:7d99a8c31fda37b91d3a3b4d73cac3b3') (7d99a8c31fda37b91d3a3b4d73cac3b3)
11:47:50 Job OK, result = u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py", line 122, in run\n    data = sous_chef.cook()\n  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 126, in cook\n    raise SousChefExecError(format_exc())\nSousChefExecError: Traceback (most recent call last):\n  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 122, in cook\n    data = self.load(data)  # load the data.\n  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 507, in load\n    status_resp = self.api.content.bulk_create_summary(data=d)\n  File "/opt/newslynx/newslynx-core/newslynx/client.py", line 737, in bulk_create_summary\n    return self._request(\'POST\', url, params=params, data=data)\n  File "/opt/newslynx/newslynx-core/newslynx/client.py", line 93, in _request\n    return self._format_response(resp, err)\n  File "/opt/newslynx/newslynx-core/newslynx/client.py", line 162, in _format_response\n    raise err(d[\'message\'])\nRequestError: Bulk endpoints require a list of json objects.\n\n'
11:47:50 Result is kept for 60 seconds
11:47:50
11:47:50 *** Listening on recipe...
11:48:15 Job OK, result = u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py", line 122, in run\n    data = sous_chef.cook()\n  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 126, in cook\n    raise SousChefExecError(format_exc())\nSousChefExecError: Traceback (most recent call last):\n  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 122, in cook\n    data = self.load(data)  # load the data.\n  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 420, in load\n    status_resp = self.api.content.bulk_create_summary(data=d)\n  File "/opt/newslynx/newslynx-core/newslynx/client.py", line 737, in bulk_create_summary\n    return self._request(\'POST\', url, params=params, data=data)\n  File "/opt/newslynx/newslynx-core/newslynx/client.py", line 93, in _request\n    return self._format_response(resp, err)\n  File "/opt/newslynx/newslynx-core/newslynx/client.py", line 162, in _format_response\n    raise err(d[\'message\'])\nRequestError: Bulk endpoints require a list of json objects.\n\n'
11:48:15 Result is kept for 60 seconds
```

**Comment by mhkeller** [comment]
fyi adding the `ga:` prefix was done via

``` py
        prepend_ga_str = lambda item: 'ga:{}'.format(item)
        ga_metric_names = map(prepend_ga_str, self.METRICS.keys())
        ga_dimension_names = map(prepend_ga_str, self.DIMENSIONS.keys())
```

That means the key is those dicts no longer corresponds, however.

**Comment by mhkeller** [comment]
I tried also changing the keys in the `METRICS` and `DIMENSIONS` dicts to include the `ga:` prefix but that led to other errors. EDITED with fuller tracebacks.

```
12:10:10 *** Listening on recipe...
12:13:57 recipe: newslynx.merlynne.run(u'newslynx_sc_google_analytics.ContentTimeseries', 22, 'newslynx-merlynne-kwargs:4d4a6b8076fd015e42b2717d4b660697') (4d4a6b8076fd015e42b2717d4b660697)
12:14:02 Job OK, result = u'Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py", line 122, in run
    data = sous_chef.cook()
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 126, in cook
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 122, in cook
    data = self.load(data)  # load the data.
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 278, in load
    d = list(data)
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 80, in serialize
    for item in data:
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 158, in run
    for row in self.format(data, prof):
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 266, in format
    for r in self.pre_format(data, prof):
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 248, in pre_format
    row[\'datetime\'] = self.format_date(row[\'datetime\'], tz=tz)
    KeyError: \'datetime\'

'
12:14:02 Result is kept for 60 seconds
12:14:02
12:14:02 *** Listening on recipe...
12:14:03 recipe: newslynx.merlynne.run(u'newslynx_sc_google_analytics.ContentDeviceSummaries', 23, 'newslynx-merlynne-kwargs:fc086f071aef8bcb9cede6a4745644e2') (fc086f071aef8bcb9cede6a4745644e2)
12:14:07 Job OK, result = u'Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py", line 122, in run
    data = sous_chef.cook()
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 126, in cook
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 122, in cook
    data = self.load(data)  # load the data.
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 496, in load
    d = list(data)
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 80, in serialize
    for item in data:
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 158, in run
    for row in self.format(data, prof):
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 478, in format
    for row in self.pre_format(data, prof):
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 470, in pre_format
    row[\'device\'] = row[\'device\'].lower()
    KeyError: \'device\'

'
12:14:07 Result is kept for 60 seconds
12:14:07
12:14:07 *** Listening on recipe...
12:14:08 recipe: newslynx.merlynne.run(u'newslynx_sc_google_analytics.ContentDomainFacets', 24, 'newslynx-merlynne-kwargs:79a48cc7249e481f69bd7f2957b2881b') (79a48cc7249e481f69bd7f2957b2881b)
12:14:17 Job OK, result = u'Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newslynx/merlynne.py", line 122, in run
    data = sous_chef.cook()
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 126, in cook
    raise SousChefExecError(format_exc())
    SousChefExecError: Traceback (most recent call last):
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 122, in cook
    data = self.load(data)  # load the data.
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 413, in load
    d = list(data)
  File "/opt/newslynx/newslynx-core/newslynx/sc/__init__.py", line 80, in serialize
    for item in data:
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 158, in run
    for row in self.format(data, prof):
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 388, in format
    for row in self.pre_format(data, prof):
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 379, in pre_format
    row = self.parse_referrer(row)
  File "/root/.newslynx/sous-chefs/newslynx-sc-google-analytics/newslynx_sc_google_analytics/__init__.py", line 323, in parse_referrer
    elif \'t.co\' in referrer:
    TypeError: argument of type \'NoneType\' is not iterable

'
```

**Comment by abelsonlive** [comment]
Yeah, that's because those dicts are also being using to change the column names. The errors above suggest that stijn is also now parsing the raw date strings from google analytics into datetime objects. will investigate

**Comment by mhkeller** [comment]
thanks. we could also try the strategy of rolling back to the version of google-analytics that this was written for. do you have that version / foresee problems with that?

**Comment by abelsonlive** [comment]
I just ran all three GA sous chefs without incident locally after this change:

https://github.com/newslynx/newslynx-sc-google-analytics/commit/5afc026fddf6a50eabf26934e515e5295f286687#diff-e24ec61755ed0af0f9761bd9a007396fR224

**NOTE**: This was for mcdonalds.hiphop and a not production user.

**Comment by abelsonlive** [comment]
successfully tested on a production user.

**Comment by mhkeller** [comment]
they all run stably! hoooraay 🌟

getting null on the below article metrics for some still. 

![screen shot 2015-09-12 at 06 20 06 am](https://cloud.githubusercontent.com/assets/498744/9826585/6aeeecc2-5916-11e5-9dbd-ff0dcbde4a89.png)

i refreshed the following recipes, is there one im missing?

internal-refresh-content-comparisons
internal-refresh-content-summary-metrics
google-analytics-to-content-domain-facets
google-analytics-to-content-device-summaries
google-analytics-to-content-timeseries

Is there something like `internal-refresh-content-metrics`

Note, the timeseries for these articles is still valid

![screen shot 2015-09-12 at 06 24 36 am](https://cloud.githubusercontent.com/assets/498744/9826664/fc760dec-5916-11e5-8ecd-95ac30db6af2.png)

**Comment by abelsonlive** [comment]
just try refreshing the summary metrics again:

```
$ newslynx api content refresh-summaries org=2
```

**Comment by abelsonlive** [comment]
FYI: that's basically all the `internal-refresh-content-summary-metrics` recipe does anyways. It's just there to force refresh the summary metrics every hour.

**Comment by abelsonlive** [comment]
This seemed to fix it (same as the cli command above)

```
$ curl -X PUT http://{prod-url}/api/v1/content/summary\?apikey\={apikey}\&org\=2
```

**Comment by mhkeller** [comment]
Fixed!
