### ISSUE TITLE
local dev install error

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#116]
running locally i do

```
dropdb newslynx
createdb newslynx
python setup.py install
newslynx init
```

and i get the following. running `newslynx init` again doesn't fix the error or rerunning `pip install .` and then `newslynx init`.

```
00:13:49 | newslynx.tasks.default-97 | Creating sous chef: "internal-refresh-content-summary-metrics"
00:13:49 | newslynx.cli.init-111 | Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/cli/init.py", line 106, in run
    default.org()
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/tasks/default.py", line 59, in org
    sous_chefs(org)
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/tasks/default.py", line 91, in sous_chefs
    for sc, fp in init.load_sous_chefs():
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/init.py", line 93, in load_sous_chefs
    for sc, fp in findsc(sous_chef_dir):
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/init.py", line 89, in findsc
    sc = sous_chef_schema.load(fp)
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/models/sous_chef_schema.py", line 50, in load
    raise SousChefSchemaError(msg)
SousChefSchemaError: Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/models/sous_chef_schema.py", line 47, in load
    return validate(sc, fp)
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/models/sous_chef_schema.py", line 99, in validate
    raise SousChefSchemaError(msg)
SousChefSchemaError: Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/models/sous_chef_schema.py", line 74, in validate
    _validate_python_sous_chef(sc)
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/models/sous_chef_schema.py", line 248, in _validate_python_sous_chef
    _raise_sous_chef_schema_error(sc, msg)
  File "/Users/mike/.virtualenvs/newslynx/lib/python2.7/site-packages/newslynx-1.1.5-py2.7.egg/newslynx/models/sous_chef_schema.py", line 279, in _raise_sous_chef_schema_error
    raise SousChefSchemaError(msg)
SousChefSchemaError: There were problems validating SousChef 'facebook-page-to-event': newslynx_sc_facebook.events is not importable. Here's the error: No module named newslynx_sc_facebook.events

failed on file /Users/mike/.newslynx/sous-chefs/newslynx-sc-facebook/newslynx_sc_facebook/facebook_page_to_event.yaml

failed on file /Users/mike/.newslynx/sous-chefs/newslynx-sc-facebook/newslynx_sc_facebook/facebook_page_to_event.yaml
```

**Comment by mhkeller** [comment]
install works on automation, however, so must be something in the steps / flow

**Comment by abelsonlive** [comment]
as per the [README](https://github.com/newslynx/newslynx-core#initialize-the-database-super-user-and-install-default-sous-chefs-tags-and-recipes), you use `make app_install` now which also install's the sous chefs.

**Comment by mhkeller** [comment]
Cool
