### ISSUE TITLE
MAX_CHUNK_SIZE is not defined on `make update`

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#117]
```
failed: [newslynx] => {"changed": true, "cmd": ["make", "app_install"], "delta": "0:00:09.019512", "end": "2015-09-06 16:26:56.181968", "rc": 2, "start": "2015-09-06 16:26:47.162456", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/local/bin/newslynx", line 9, in <module>
    load_entry_point('newslynx==1.1.5', 'console_scripts', 'newslynx')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/newslynx/cli/__init__.py", line 15, in <module>
    from newslynx.cli.common import parse_runtime_args, LOGO
  File "/usr/local/lib/python2.7/dist-packages/newslynx/cli/common.py", line 5, in <module>
    from newslynx.lib import serialize
  File "/usr/local/lib/python2.7/dist-packages/newslynx/lib/serialize.py", line 20, in <module>
    from newslynx.lib.search import SearchString
  File "/usr/local/lib/python2.7/dist-packages/newslynx/lib/search.py", line 34, in <module>
    from newslynx.util import uniq
  File "/usr/local/lib/python2.7/dist-packages/newslynx/util.py", line 79, in <module>
    def chunk_list(l, n=MAX_CHUNK_SIZE):
NameError: name 'MAX_CHUNK_SIZE' is not defined
make: *** [app_install] Error 1
stdout: make[1]: Entering directory `/opt/newslynx/newslynx-core'
creating a fresh install of newslynx...
make[1]: Leaving directory `/opt/newslynx/newslynx-core'
make[1]: Entering directory `/opt/newslynx/newslynx-core'
make[1]: Leaving directory `/opt/newslynx/newslynx-core'
```

**Comment by mhkeller** [comment]
@abelsonlive if there's a pointer to where i could fix this i can take a look. should it be defined in config.yaml or defaults.py. once i run `make update` i can test if the pooling issue is still visible.

**Comment by mhkeller** [comment]
Fixed in https://github.com/newslynx/newslynx-core/commit/bff341cdd6a6ee69cf5d193280a9d9099c7bf16f

When `chunk_list` fn was added to `util.py`, it didn't carry over config variable from `load.py`
https://github.com/newslynx/newslynx-core/commit/454cf121ba1faa14a296df960721ff5f245287b4
