### ISSUE TITLE
migration error: attribute refresh operation cannot proceed\n", "error": "DetachedInstanceError"}

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#159]
```
23:42:50 | migration-206 | Migrating Facebook Page Promotion Recipe for: WisWatch
Traceback (most recent call last):
  File "bin/migrate", line 652, in <module>
    migrate.all()
  File "bin/migrate", line 635, in all
    self.recipes()
  File "bin/migrate", line 336, in recipes
    self.settings_to_recipes()
  File "bin/migrate", line 208, in settings_to_recipes
    'facebook-page-to-event-promotion', page_id=fb_page['page_id'])
  File "/usr/local/lib/python2.7/dist-packages/newslynx/client.py", line 538, in update
    return self._request('PUT', url, data=kw, params=params)
  File "/usr/local/lib/python2.7/dist-packages/newslynx/client.py", line 93, in _request
    return self._format_response(resp, err)
  File "/usr/local/lib/python2.7/dist-packages/newslynx/client.py", line 161, in _format_response
    raise ClientError(resp.content)
newslynx.exc.ClientError: {"status_code": 500, "message": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python2.7/dist-packages/newslynx/views/decorators.py\", line 35, in decorated_function\n    return f(*args, **kw)\n  File \"/usr/local/lib/python2.7/dist-packages/newslynx/views/decorators.py\", line 75, in decorated_function\n    return f(*args, **kw)\n  File \"/usr/local/lib/python2.7/dist-packages/newslynx/views/api/recipes_api.py\", line 311, in update_recipe\n    return jsonify(r)\n  File \"/usr/local/lib/python2.7/dist-packages/newslynx/lib/serialize.py\", line 208, in jsonify\n    data = encoder(refs=refs).encode(obj)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 207, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 270, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/local/lib/python2.7/dist-packages/newslynx/lib/serialize.py\", line 183, in default\n    return obj.to_dict()\n  File \"/usr/local/lib/python2.7/dist-packages/newslynx/models/recipe.py\", line 121, in to_dict\n    'id': self.id,\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py\", line 237, in __get__\n    return self.impl.get(instance_state(instance), dict_)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py\", line 573, in get\n    value = state._load_expired(state, passive)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py\", line 480, in _load_expired\n    self.manager.deferred_scalar_loader(self, toload)\n  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py\", line 610, in load_scalar_attributes\n    (state_str(state)))\nDetachedInstanceError: Instance <Recipe at 0x7fc9aa2a8250> is not bound to a Session; attribute refresh operation cannot proceed\n", "error": "DetachedInstanceError"}
```

**Comment by mhkeller** [comment]
Seems like the opposite of too many clients error

**Comment by abelsonlive** [comment]
I think that should fix it.

**Comment by mhkeller** [comment]
testing...

**Comment by mhkeller** [comment]
fixed!
