### ISSUE TITLE
unknown migration error

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#160]
More info here https://github.com/newslynx/issue-tracker/issues/527

```
03:14:35 | migration-534 | loading 57 events for recipe facebook-page-to-event-promotion
Traceback (most recent call last):
  File "bin/migrate", line 652, in <module>
    migrate.all()
  File "bin/migrate", line 636, in all
    self.all_article_details()
  File "bin/migrate", line 622, in all_article_details
    self.load_sum_metrics(sum_metrics)
  File "bin/migrate", line 553, in load_sum_metrics
    list(self.api.jobs.poll(**resp))
  File "/usr/local/lib/python2.7/dist-packages/newslynx/client.py", line 980, in poll
    return list(gen())
  File "/usr/local/lib/python2.7/dist-packages/newslynx/client.py", line 976, in gen
    raise JobError(d.get('message', ''))
newslynx.exc.JobError: An unknown error occurred.
```

**Comment by abelsonlive** [comment]
FYI: You can also check the the API logs / worker logs for more info.
