### ISSUE TITLE
global name 'distinct' is not defined

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#57]
```
ERROR:newslynx.core:Exception on /api/v1/content [GET]
Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mike/.virtualenvs/nl/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/decorators.py", line 35, in decorated_function
    return f(*args, **kw)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/decorators.py", line 75, in decorated_function
    return f(*args, **kw)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/api/content_api.py", line 440, in search_content
    event_ids = db.session.query(distinct(content_items_events.c.event_id))\
NameError: global name 'distinct' is not defined
```

**Comment by abelsonlive** [comment]
closed
