### ISSUE TITLE
Error on newslynx init

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#58]
Ran

```
dropdb newslynx && createdb newslynx && pip install --editable . && newslynx init && newslynx dev gen-random-data && newslynx debug
```

```
 / \ / \ / \ / \ / \ / \ / \ / \
( n | e | w | s | l | y | n | x )
 \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/

Creating database "postgres://@localhost:5432/newslynx"
Creating super user "merlynne@newslynx.org"
(Re)Loading SQL Extensions
Importing Sous Chef "rss-feed-to-article"
Importing Sous Chef "facebook-page-to-event"
14:22:30 | SousChefSchemaError : There were problems validating SousChef 'reddit-search-content-item-links-to-event': newslynx.sc.events.reddit is not importable.
14:22:30 | Traceback (most recent call last):
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/cli/init.py", line 67, in run
    for sc in load_sous_chefs():
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/init.py", line 60, in load_sous_chefs
    yield load_sous_chef(fp)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/init.py", line 49, in load_sous_chef
    return sous_chef_schema.validate(sc)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/models/sous_chef_schema.py", line 51, in validate
    _validate_python_sous_chef(sc)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/models/sous_chef_schema.py", line 215, in _validate_python_sous_chef
    _raise_sous_chef_schema_error(sc, msg)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/models/sous_chef_schema.py", line 246, in _raise_sous_chef_schema_error
    raise SousChefSchemaError(msg)
SousChefSchemaError: There were problems validating SousChef 'reddit-search-content-item-links-to-event': newslynx.sc.events.reddit is not importable.
```

**Comment by mhkeller** [comment]
`pip install praw` fixed this
