### ISSUE TITLE
Tuple out of range

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#71]
On this url

```
http://localhost:5000/api/v1/events?sous_chef_ids=twitter-search-content-items-to-event&per_page=10&content_item_ids=2&apikey=mj&org=1
```

```
INFO:werkzeug:127.0.0.1 - - [22/Jul/2015 22:15:44] "GET /api/v1/events?sous_chef_ids=-twitter-search-content-items-to-event&per_page=10&content_item_ids=2&apikey=mj&org=1 HTTP/1.1" 500 -
ERROR:newslynx.core:Exception on /api/v1/events [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/decorators.py", line 35, in decorated_function
    return f(*args, **kw)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/decorators.py", line 75, in decorated_function
    return f(*args, **kw)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/api/events_api.py", line 206, in search_events
    arg_list('sous_chef_ids', default=[], typ=int, exclusions=True)
  File "/Users/mike/wrk/projects/newslynx/newslynx-core/newslynx/views/util.py", line 124, in arg_list
    .format(value), i, name, type_string)
IndexError: tuple index out of range
```

**Comment by abelsonlive** [comment]
the option should be `sous_chefs` now.
