### ISSUE TITLE
error on event creation

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#98]
![screen shot 2015-08-27 at 12 40 19 pm](https://cloud.githubusercontent.com/assets/498744/9529912/eaa76398-4cca-11e5-899e-2d1e3e724ef8.png)

**Comment by abelsonlive** [comment]
Could you post the trace from the api logs?

**Comment by mhkeller** [comment]
```
15:39:36 | newslynx.core-1423 | Exception on /api/v1/events [POST]
Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/views/decorators.py", line 35, in decorated_function
    return f(*args, **kw)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/views/decorators.py", line 75, in decorated_function
    return f(*args, **kw)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/views/api/events_api.py", line 344, in create_event
    queued=False)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/tasks/load.py", line 52, in events
    return bulkload(data, **kw)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/tasks/load.py", line 126, in bulkload
    return ingest.source(data, **kw)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/tasks/ingest.py", line 74, in source
    return fx.get(src)(data, **kw)
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/tasks/ingest.py", line 156, in events
    _clean()
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/newslynx/tasks/ingest.py", line 117, in _clean
    for obj in p.imap_unordered(__prepare, data):
  File "/Users/mike/.virtualenvs/bcd/lib/python2.7/site-packages/gevent-1.0.2-py2.7-macosx-10.10-intel.egg/gevent/pool.py", line 222, in next
    raise value.exc
AttributeError: 'module' object has no attribute 'html'
```

**Comment by abelsonlive** [comment]
This was taken care of by a recent push.
